# Generated by Django 5.2.12 on 2026-04-06 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('institution_type', models.CharField(choices=[('higher', 'Higher education'), ('professional', 'Professional education')], db_index=True, max_length=20)),
                ('department', models.CharField(max_length=255)),
                ('employment', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('education', models.CharField(choices=[('vocational', 'Vocational / technical diploma'), ('bachelor', 'Bachelor’s degree'), ('master', 'Master’s degree'), ('phd', 'Doctoral degree (PhD / equivalent)')], max_length=20)),
                ('experience', models.TextField()),
                ('cover_letter', models.TextField()),
                ('consent', models.BooleanField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vacancies.vacancy')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
