# Generated by Django 5.2.12 on 2026-04-06 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.FileField(blank=True, help_text='PDF, DOC, or DOCX. Maximum size is enforced on the public application form.', null=True, upload_to='applications/cv/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx'))]),
        ),
    ]
