# Generated by Django 5.2.12 on 2026-04-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_application_cv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Arizalar', 'verbose_name_plural': 'Arizalar'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'Vakansiyalar', 'verbose_name_plural': 'Vakansiyalar'},
        ),
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(verbose_name='Motivatsion xat'),
        ),
        migrations.AlterField(
            model_name='application',
            name='education',
            field=models.CharField(choices=[('vocational', 'Kasb-hunar / texnik diplom'), ('bachelor', 'Bakalavr darajasi'), ('master', 'Magistr darajasi'), ('phd', 'Doktorlik darajasi (PhD yoki unga teng)')], max_length=20, verbose_name='Ta’lim darajasi'),
        ),
        migrations.AlterField(
            model_name='application',
            name='experience',
            field=models.TextField(verbose_name='Ish tajribasi'),
        ),
        migrations.AlterField(
            model_name='application',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='To‘liq ism'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=40, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateField(verbose_name='Ariza muddati'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='department',
            field=models.CharField(max_length=255, verbose_name='Bo‘lim'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employment',
            field=models.CharField(max_length=120, verbose_name='Ish turi'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='institution_type',
            field=models.CharField(choices=[('higher', "Oliy ta'lim"), ('professional', "Kasbiy ta'lim")], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location',
            field=models.CharField(max_length=120, verbose_name='Manzil'),
        ),
    ]
