# Generated by Django 5.2.12 on 2026-04-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_alter_application_options_alter_vacancy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='institution',
            field=models.CharField(default='Toshkent kimyo-texnologiya instituti', max_length=255, verbose_name='Muassasa'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Ish nomi'),
        ),
    ]
