# Generated by Django 5.2.12 on 2026-04-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_alter_vacancy_institution_alter_vacancy_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='institution_type',
            field=models.CharField(choices=[('higher', "Oliy ta'lim"), ('professional', "Kasbiy ta'lim")], db_index=True, max_length=20, verbose_name="Ta'lim turi"),
        ),
    ]
