# Generated by Django 5.2.12 on 2026-04-10 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_alter_vacancy_institution_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Yuborilgan'), ('under_review', 'Ko‘rib chiqilmoqda'), ('shortlisted', 'Tanlov ro‘yxatida'), ('rejected', 'Rad etilgan'), ('accepted', 'Qabul qilingan')], db_index=True, default='submitted', max_length=20, verbose_name='Holat'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_applications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'vacancy'), name='uniq_application_user_per_vacancy'),
        ),
    ]
